version: '2'
services:
  web:
    build: ./flask-app/.
    ports:
      - "5000:5000"
      - "8000:8000"
    volumes:
      - ./flask-app/:/code
    environment:
      - FLASK_APP=app.py
  mysql:
    build: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#  load-generator:
#   image: "neotys/neoload-loadgenerator"
#   ports:
#     - "7100:7100"
  locust:
    image: hakobera/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust/locustfile.py:/test/locustfile.py
    environment:
      - TARGET_URL=http://web
      - LOCUST_MODE=standalone
      - SCENARIO_FILE=/test/locustfile.py
  controller:
    build: ./controller/.
    ports:
      - "9000:9000"
    volumes:
      - ./controller/:/code
    environment:
      - FLASK_APP=app.py
#  influxdb:
#    image: "influxdb"
#    ports:
#     - "8086:8086"
#     - "2003:2003"
#    environment:
#      - INFLUXDB_GRAPHITE_ENABLED=true
#  graphana:
#    image: "grafana/grafana"
#    environment:
#      - INFLUXDB_HOST=influxdb
#      - INFLUXDB_NAME=clusterSim
#      - INFLUXDB_USER=cluster
#      - INFLUXDB_PASS=clusterPass
#    ports:
#     - "3000:3000"
